@startuml package-diagram

title libcpptest package diagram

package "Public Interface" as API

package setup {
   [Sandbox] 
}

package integration_test {
    [MultiTest]
    [SingleTest]
    [TestCase]
    [Skeleton]
    [Fail]
}

package <<external>> {
    package libcpplog {
        [Logger]
    }
}

API ..> Fail : <<import>>
API ..> MultiTest : <<import>>
API ..> SingleTest : <<import>>
API ..> TestCase : <<import>>

SingleTest ..> Skeleton : <<access>>
MultiTest ..> Skeleton: <<access>>

SingleTest ..> Logger : <<import>>
MultiTest ..> Logger: <<import>>

Skeleton ..> Sandbox : <<access>>

@enduml